### ISSUE TITLE
CSS id vs class

### ISSUE THREAD

**Issue by gonzoguajardo** [geodrummer/WSB-Site#16]
You don't have to fix this for the merge to master but I saw this and wanted to bring it up. Usually you use the `id` property for a unique element and `class` for a group of elements. 

So in your schedule page, you have code like `<thead id="Days">` and `<th scope="row" id="Empolyees">Gabriel</th>`. There should not be another html element with the `Days` or the `Employees` id. It is bad practice if you try and use the id for multiple elements. Instead use a class. You are already using a class in your css, `.active`, so you know how to style classes already. Make sure to update your css after you change these to classes. 

Also most developers use lowercase for id's and classes. If you need to use more than one word, use a hyphen (e.g. `id="unique-day"`, `class="ws-employees"`, `id="first-header"`, `class="headers"`)

**Comment by geodrummer** [comment]
wait do i have to fix it even though we arent going to use it..didnt you say for me to try the js

**Comment by gonzoguajardo** [comment]
This was more for awareness. If you understand what I am trying to convey then you can close the issue.
