### ISSUE TITLE
index.html file needed

### ISSUE THREAD

**Issue by gonzoguajardo** [geodrummer/WSB-Site#9]
Most web servers look for `index.html` as the file to be served when you don't specify a file name. Look at Apache's [documentation ](http://ec2-18-219-230-185.us-east-2.compute.amazonaws.com/) under "Web Site Content" for more information. So for example, when I sent you the ec2 link, it was _http://ec2-18-219-230-185.us-east-2.compute.amazonaws.com/WSB%20Thank%20You.html_. If you go to _http://ec2-18-219-230-185.us-east-2.compute.amazonaws.com/_ (notice I did not specify a file name this time) you will see the `index.html` I created on the server. You need to add a `index.html` file to your project. It will be the "main" page. 

Take a look at [mine](https://github.com/garGONZO/beccaandgonzo.love-client/blob/master/src/index.html). I just set the title and icon (the heart icon you see in the chrome tab when you visit my site) and then I reference another html page in the body with the angular framework.

**Comment by geodrummer** [comment]
by main page, do you mean like homepage??

**Comment by gonzoguajardo** [comment]
Main page. Homepage. Whatever you want to call it. The page that gets served when you hit the root domain (nothing after http://ec2-18-219-230-185.us-east-2.compute.amazonaws.com/). 

For example look at these HEB links.  https://www.heb.com/   and https://www.heb.com/static-page/coupons  Right now you have nothing for www.heb.com (the root domain).

**Comment by geodrummer** [comment]
can i fix it by remnaming the homepage to index.html

**Comment by gonzoguajardo** [comment]
Yup, that would the quickest way. 
Maybe when you are renaming that one, you can get rid of the spaces in the other file names? :p
